POST http://localhost:3000/create/users HTTP/1.1
content-type: application/json

{
    "first_name": "Tommy",
    "last_name": "Frishberg",
    "screen_name": "tomtom",
    "dob": "1975-01-21"
}

###

GET http://localhost:3000/retrieve/single-cosmetic/1 HTTP/1.1

###

GET http://localhost:3000/retrieve/users HTTP/1.1